version: '3'
services:
  mySql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=topcar
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql